---

- name: Remove other installed menubar hiders.
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: absent
  loop: "{{ hiddenbar__uninstall_casks }}"

- name: Install Application to hide bar.
  community.general.homebrew_cask:
    name: "{{ hiddenbar__caskname }}"
    state: present

- name: "Configure menubar hider application: {{ hiddenbar_default.description | d('Misc') }}."
  community.general.osx_defaults:
    domain: "{{ hiddenbar_default.domain | d(hiddenbar__defaults_domain) }}"
    key: "{{ hiddenbar_default.key }}"
    type: "{{ hiddenbar_default.type }}"
    value: "{{ hiddenbar_default.value }}"
    state: "{{ hiddenbar_default.state | d('present') }}"
  loop: "{{ hiddenbar__defaults }}"
  loop_control:
    loop_var: hiddenbar_default
