---
packages__homebrew_packages_extra:
  - azure-cli
  - d2
  - helm
  - ipmitool
  - lftp
  - node
  - packer
  - packer-completion
  - sipcalc
  - stern
  - terraform

packages__homebrew_blacklist_extra:
  - arduino-cli
  - cfssl
  - multitail

packages__homebrew_casks_extra:
  - citrix-workspace
  - firefox
  - flexoptix
  - jabra-direct
  - keycastr
  - lens
  - mattermost
  - microsoft-edge
  - microsoft-teams
  - postman
  - rocket-chat
  - sequel-ace
  - slack
  - tunnelblick
  - virtualbox
  - vitalsource-bookshelf
  - webex-meetings
  - xbar

packages__homebrew_casks_blacklist_extra:
  - arduino
  - displaylink
  - finicky
  - rocket-chat
  - thunderbird
  - webcatalog
  - xquartz

packages__mas_extra:
  - { id: 1532419400, name: MeetingBar }
  - { id: 1295203466, name: Microsoft Remote Desktop 10 }
  - { id: 1230249825, name: VMware Remote Console }
  - { id: 462058435, name: Microsoft Excel }
  - { id: 462062816, name: Microsoft PowerPoint }
  - { id: 985367838, name: Microsoft Outlook }
  - { id: 462054704, name: Microsoft Word }

dockitems_remove:
  - App Store
  - Calendar
  - Contacts
  - FaceTime
  - Google Chrome
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Microsoft Teams classic
  - Notes
  - Photos
  - Reminders
  - Safari
  - System Preferences
  - iBooks
  - iTiTermrm
  - iTunes

dockitems_persist:
  - name: Ghostty
    path: /Applications/Ghostty.app
    pos: 1
  - name: Firefox
    path: /Applications/Firefox.app
    pos: 2
  - name: Microsoft Outlook
    path: /Applications/Microsoft Outlook.app
    pos: 3
  - name: Mattermost
    path: /Applications/Mattermost.app
    pos: 4
  - name: Spotify
    path: /Applications/Spotify.app
    pos: 5
  - name: Microsoft Teams
    path: /Applications/Microsoft Teams.app
    pos: 6
  - name: Visual Studio Code
    path: /Applications/Visual Studio Code.app
    pos: 7

osx__wallpaper: ~/Nextcloud_p/Wallpapers/Desert.heic
terminal__transparency: 0.05
terminal__window_type: 0
