---

dock__tilesize: 22

packages__homebrew_casks_extra:
  - openscad
  - prusaslicer
  - vlc

dock__remove_items:
  - App Store
  - Contacts
  - FaceTime
  - Launchpad
  - Maps
  - Messages
  - Notes
  - Reminders
  - Safari
  - System Preferences
  - iBooks
