---
packages__homebrew_packages_extra:
  - docker-completion
  - docker-compose-completion

packages__homebrew_casks_extra:
  - mattermost
  - remote-desktop-manager
  - kitematic
  - tunnelblick
  - skype-for-business

packages__mas_extra:
  - { id: 1295203466, name: 'Microsoft Remote Desktop 10' }

dock__remove_items:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Calendar
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences

dock__items:
  - name: iTerm
    path: "/Applications/iTerm.app"
  - name: Firefox
    path: "/Applications/Firefox.app"
  - name: Microsoft Outlook
    path: "/Applications/Microsoft Outlook.app"
  - name: Remote Desktop Manager
    path: "/Applications/Remote Desktop Manager.app"
  - name: Mattermost
    path: "/Applications/Mattermost.app"
  - name: Skype for Business
    path: "/Applications/Skype for Business.app"
  - name: Spotify
    path: "/Applications/Spotify.app"
