---
packages__homebrew_taps_extra:
  - zaquestion/tap

packages__homebrew_packages_extra:
  - rust
  - rustc-completion
  - gnupg
  - exercism
  - bats
  - maven
  - dos2unix
  - lab
  - awscli
  - minikube
  - docker-completion
  - docker-compose-completion

packages__homebrew_casks_extra:
  - mattermost
  - kitematic
  - tunnelblick
  - skype-for-business
  - slack
  - virtualbox
  - virtualbox-extension-pack
  - vagrant
  - macdown
  - sequel-pro
  - airtame
  - docker
  - microsoft-teams
  - jabra-direct

packages__mas_extra:
  - {id: 1295203466, name: 'Microsoft Remote Desktop 10'}
  - {id: 1230249825, name: 'VMware Remote Console'}

dock__remove_items:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Calendar
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Firefox

dock__items:
  - name: iTerm
    path: "/Applications/iTerm.app"
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
  - name: Microsoft Outlook
    path: "/Applications/Microsoft Outlook.app"
  - name: Remote Desktop Manager
    path: "/Applications/Remote Desktop Manager.app"
  - name: Mattermost
    path: "/Applications/Mattermost.app"
  - name: Skype for Business
    path: "/Applications/Skype for Business.app"
  - name: Spotify
    path: "/Applications/Spotify.app"
