---
packages__homebrew_packages_extra:
  - lftp
  - multitail
  - node
  - packer
  - packer-completion
  - sipcalc

packages__homebrew_casks_extra:
  - airtame
  - displaylink
  - docker
  - jabra-direct
  - keycastr
  - macdown
  - mattermost
  - microsoft-edge
  - microsoft-teams
  - sequel-pro
  - skitch
  - slack
  - thunderbird
  - tunnelblick
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - xbar
  - xquartz

packages__mas_extra:
  - {id: 1532419400, name: 'MeetingBar'}
  - {id: 1295203466, name: 'Microsoft Remote Desktop 10'}
  - {id: 1230249825, name: 'VMware Remote Console'}

dockitems_remove:
  - App Store
  - Calendar
  - Contacts
  - FaceTime
  - Firefox
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Notes
  - Photos
  - Reminders
  - Safari
  - System Preferences
  - iBooks
  - iTunes

dockitems_persist:
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 2
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 3
  - name: Microsoft Outlook
    path: "/Applications/Microsoft Outlook.app"
    pos: 4
  - name: Remote Desktop Manager
    path: "/Applications/Remote Desktop Manager.app"
    pos: 5
  - name: Mattermost
    path: "/Applications/Mattermost.app"
    pos: 6
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 7
  - name: Microsoft Teams
    path: "/Applications/Microsoft Teams.app"
    pos: 8
