---

dock__tilesize: 22

packages__homebrew_casks_extra:
  - openscad
  - prusaslicer
  - vlc

packages__mas_extra:
  - { id: 948660805, name: 'AusweisApp2' }

dockitems_persist:
  - name: iTerm
    pos: 2
  - name: Safari
    pos: 3
  - name: Mail
    pos: 4
  - name: Calendar
    pos: 5
  - name: Photos
    pos: 6
  - name: Telegram
    path: "/Applications/Telegram.app/"
    pos: 7
  - name: Spotify
    pos: 8
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app/"
    pos: 9

dockitems_remove:
  - App Store
  - Contacts
  - FaceTime
  - Launchpad
  - Maps
  - Messages
  - Notes
  - Reminders
  - System Preferences
  - iBooks