---
packages__homebrew_packages_extra:
  - awscli
  - azure-cli
  - bfg
  - d2
  - gitlab-runner
  - govc
  - helm
  - ipmitool
  - lftp
  - node
  - packer
  - packer-completion
  - php
  - sipcalc
  - stern
  - terraform

packages__homebrew_blacklist_extra:
  - arduino-cli
  - cfssl
  - multitail

packages__homebrew_casks_extra:
  - citrix-workspace
  - firefox
  - flexoptix
  - jabra-direct
  - keycastr
  - lens
  - mattermost
  - microsoft-edge
  - microsoft-teams-classic
  - postman
  - sequel-ace
  - skitch
  - slack
  - tunnelblick
  - virtualbox
  - vitalsource-bookshelf
  - webex-meetings
  - xbar

packages__homebrew_casks_blacklist_extra:
  - arduino
  - displaylink
  - finicky
  - rocket-chat
  - thunderbird
  - webcatalog
  - xquartz

packages__mas_extra:
  - { id: 1532419400, name: MeetingBar }
  - { id: 1295203466, name: Microsoft Remote Desktop 10 }
  - { id: 1230249825, name: VMware Remote Console }
  - { id: 823766827, name: OneDrive }

dockitems_remove:
  - App Store
  - Calendar
  - Contacts
  - FaceTime
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Notes
  - Photos
  - Reminders
  - Safari
  - System Preferences
  - iBooks
  - iTunes
  - Google Chrome
  - Microsoft Teams classic

dockitems_persist:
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 1
  - name: Firefox
    path: /Applications/Firefox.app
    pos: 2
  - name: Microsoft Outlook
    path: /Applications/Microsoft Outlook.app
    pos: 3
  - name: Mattermost
    path: /Applications/Mattermost.app
    pos: 4
  - name: Spotify
    path: /Applications/Spotify.app
    pos: 5
  - name: Microsoft Teams
    path: /Applications/Microsoft Teams.app
    pos: 6
  - name: Visual Studio Code
    path: /Applications/Visual Studio Code.app
    pos: 7
  - name: Hidden Bar
    path: /Applications/Hidden Bar.app
    pos: 25

osx__wallpaper: ~/Nextcloud_p/Wallpapers/Gradiant.heic
terminal__transparency: 0.05
terminal__window_type: 0

hiddenbar__full_statusbar: true
