---
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0

collections:
  - name: geerlingguy.mac
    version: 4.0.0
  - name: ansible.posix
    version: 1.5.1
  - name: community.general
    version: 6.4.0
