---
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0

collections:
  - name: geerlingguy.mac
    version: 4.0.1
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 10.0.1.0
