---
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0

collections:
  - name: geerlingguy.mac
    version: 1.4.0
  - name: ansible.posix
    version: 1.4.0
  - name: community.general
    version: 5.7.0
