---
- hosts: localhost

  pre_tasks:
    - name: Include host-specific configuration variables
      include_vars: "{{ item }}"
      with_fileglob:
        - "config.{{ ansible_hostname }}.yml"
      tags: ['always']

  roles:
    - role: packages
      tags: ['packages']
    - role: dock
      when: ansible_os_family == 'Darwin'
      tags: ['dock']
    - role: terminal
      tags: ['terminal']
    - role: osx
      when: ansible_os_family == 'Darwin'
      tags: ['osx']
    - role: yadm
      tags: ['yadm']
    - role: powershell
      tags: ['powershell']
    - role: hiddenbar
      tags: ['hiddenbar']
