---
- hosts: localhost

  pre_tasks:
    - name: Include host-specific configuration variables
      include_vars: "{{ item }}"
      with_fileglob:
        - "config.{{ ansible_hostname }}.yml"
      tags: ['always']

  roles:
    - role: 'roles/packages'
    - role: 'roles/dock'
    - role: 'roles/terminal'
    - role: 'roles/osx'
    - role: 'roles/yadm'
    - role: 'roles/powershell'

- hosts: work_linux

  pre_tasks:
    - name: Include host-specific configuration variables
      include_vars: "{{ item }}"
      with_fileglob:
        - "config.{{ ansible_hostname }}.yml"
      tags: ['always']

  roles:
    - role: 'roles/packages'
    - role: 'roles/yadm'
