---

- name: Setup workstation.
  hosts: localhost
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  pre_tasks:
    - name: Include host-specific configuration variables
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "config.{{ ansible_hostname }}.yml"
        - config.yml
      tags: [always]

  roles:
    - role: packages
      tags: [packages]
    - role: dock
      when: ansible_os_family == 'Darwin'
      tags: [dock]
    - role: terminal
      tags: [terminal]
    - role: osx
      when: ansible_os_family == 'Darwin'
      tags: [osx]
    - role: yadm
      tags: [yadm]
    - role: powershell
      tags: [powershell]
    - role: hiddenbar
      tags: [hiddenbar]
    - role: amphetamine
      tags: [amphetamine]
    - role: amethyst
      tags: [amethyst]
    - role: aerospace
      tags: [aerospace]
