---

- name: Setup workstation.
  hosts: all
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  roles:
    - role: packages
      tags: [packages]
    - role: dock
      when: ansible_os_family == 'Darwin'
      tags: [dock]
    - role: terminal
      tags: [terminal]
    - role: osx
      when: ansible_os_family == 'Darwin'
      tags: [osx]
    - role: yadm
      tags: [yadm]
    - role: powershell
      tags: [powershell]
    - role: hiddenbar
      tags: [hiddenbar]
    - role: amphetamine
      tags: [amphetamine]
    - role: amethyst
      tags: [amethyst]
    - role: aerospace
      tags: [aerospace]
    - role: docker
      tags: [docker]
    - role: wireguard
      tags: [wireguard]

- name: Run levigo specific tasks.
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  hosts: levigo
  roles:
    - role: levigo
      tags: [levigo]
    - role: tunnelblick
      tags: [tunnelblick]
