---
- hosts: localhost

  pre_tasks:
    - name: Include host-specific configuration variables
      include_vars: "{{ item }}"
      with_fileglob:
        - "config.{{ ansible_hostname }}.yml"
      tags: ['always']

  roles:
    - role: 'roles/packages'
      tags: ['packages']
    - role: 'roles/dock'
      when: ansible_os_family == 'Darwin'
      tags: ['dock']
    - role: 'roles/terminal'
      tags: ['terminal']
    - role: 'roles/osx'
      when: ansible_os_family == 'Darwin'
      tags: ['osx']
    - role: 'roles/yadm'
      tags: ['yadm']
    - role: 'roles/powershell'
      tags: ['powershell']
