---
- name: Merge configured taps for homebrew
  set_fact: homebrew_taps="{{ (packages__homebrew_taps + packages__homebrew_taps_extra )| unique }}"

- name: Merge configured packages for homebrew
  set_fact: homebrew_installed_packages="{{ (packages__homebrew_packages + packages__homebrew_packages_extra )| unique }}"

- name: Merge configured casks for homebrew
  set_fact: homebrew_cask_apps="{{ (packages__homebrew_casks + packages__homebrew_casks_extra )| unique }}"

- include_role:
    name: geerlingguy.homebrew
