---

- name: Install default packages on macOS.
  include_tasks: osx_packages.yml
  when: ansible_system == 'Darwin'

- name: Include pip tasks
  include_tasks: pip_packages.yml

- name: Install default packages on Linux.
  include_tasks: linux_packages.yml
  when: ansible_system == 'Linux'
