---

- name: Include tasks
  include_tasks: osx_packages.yml
  when: ansible_os_family == 'Darwin'
  tags: ['packages']

- name: Install default packages on Linux
  include_tasks: linux_packages.yml
  when: ansible_system == 'Linux'
