---

- name: Install default packages on macOS.
  include_tasks: osx_packages.yml
  when: ansible_system == 'Darwin'

- name: Install default packages on Linux.
  include_tasks: linux_packages.yml
  when: ansible_system == 'Linux'
