---
- name: Include homebrew-role, which uses the variables above.
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_taps: "{{ packages__homebrew_taps + packages__homebrew_taps_extra | unique | default([]) }}"
    homebrew_installed_packages: "{{ packages__homebrew_packages + packages__homebrew_packages_extra | unique | default([]) }}"
    homebrew_uninstalled_packages: "{{ packages__homebrew_blacklist + packages__homebrew_blacklist_extra | unique | default([]) }}"
    homebrew_cask_apps: "{{ packages__homebrew_casks + packages__homebrew_casks_extra | unique | default([]) }}"
    homebrew_cask_uninstalled_apps: "{{ packages__homebrew_casks_blacklist + packages__homebrew_casks_blacklist_extra | unique | default([]) }}"
  tags:
    - skip_ansible_lint

- name: Include mas-role, which uses the variables above.
  ansible.builtin.include_role:
    name: geerlingguy.mac.mas
  vars:
    mas_installed_apps: "{{ packages__mas + packages__mas_extra | unique | default([]) }}"
    mas_uninstalled_apps: "{{ packages__mas_blacklist + packages__mas_blacklist_extra | unique | default([]) }}"
  tags:
    - skip_ansible_lint
