---

- name: 'Get current value for {{ item }}'
  ansible.builtin.command: "/usr/libexec/PlistBuddy -c 'Print {{ item }}' ~/Library/Preferences/com.apple.finder.plist"
  register: osx__defaults_arrangeby_current
  changed_when: false
  check_mode: false

- name: 'Enable snap-to-grid for icons in {{ item }}'
  ansible.builtin.command: "/usr/libexec/PlistBuddy -c 'Set {{ item }} grid' ~/Library/Preferences/com.apple.finder.plist"
  when: osx__defaults_arrangeby_current.stdout != 'grid'
  notify: Restart Finder
