---

- name: Enable tap to click for this user
  community.general.osx_defaults:
    domain: 'com.apple.driver.AppleBluetoothMultitouch.trackpad'
    key: 'Clicking'
    type: 'int'
    value: '1'
    state: 'present'

- name: Enable tap to click on Login screen
  community.general.osx_defaults:
    host: 'currentHost'
    domain: 'NSGlobalDomain'
    key: 'com.apple.mouse.tapBehavior'
    type: 'int'
    value: '1'
    state: 'present'

- name: Enable tap to click on Login screen/2
  community.general.osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'com.apple.mouse.tapBehavior'
    type: 'int'
    value: '1'
    state: 'present'
