---

- name: Include geerlingguy.dock role, to configure items.
  ansible.builtin.include_role:
    name: geerlingguy.mac.dock

- name: Configure Downloads folder in Dock
  ansible.builtin.command: dockutil --add '~/Downloads' --replacing Downloads --view grid --display folder --sort datecreated
  changed_when: false

- name: Configure Dock tile size
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: "{{ dock__tilesize }}"
    state: present
  notify: Restart Dock.

- name: Lock Dock size
  community.general.osx_defaults:
    domain: com.apple.dock
    key: size-immutable
    type: bool
    value: true
    state: present
  notify: Restart Dock.
