---

- name: Get current Dock items
  shell: dockutil --list | cut -f1
  register: dock__current_items

- name: Remove unwanted items from Dock
  shell: dockutil --remove '{{ item }}'
  loop: "{{ dock__remove_items }}"
  when: item in dock__current_items.stdout_lines

- name: Add wanted items to Dock
  shell: dockutil --add '{{ item.path }}'
  loop: "{{ dock__items }}"
  when: item.name not in dock__current_items.stdout_lines

- name: Configure Dock order
  shell: dockutil --move '{{ item.name }}' --position '{{ my_idx + 1 }}'
  loop: "{{ dock__items }}"
  loop_control:
    index_var: my_idx
