---

- name: Install Aerospace window manager.
  community.general.homebrew_cask:
    name: nikitabobko/tap/aerospace
    state: present

- name: Create aerospace configuration directory.
  ansible.builtin.file:
    path: "{{ aerospace__configuration_directory }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"
    state: directory

- name: Place Aerospace configuration.
  ansible.builtin.template:
    src: aerospace.toml.j2
    dest: "{{ aerospace__configuration_directory }}/aerospace.toml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"
  notify: Reload aerospace.

- name: Tap repository for bars and borders.
  community.general.homebrew_tap:
    name: felixkratz/formulae
    state: present

- name: Install JankyBorders.
  community.general.homebrew:
    name: felixkratz/formulae/borders
    state: present

- name: Create borders configuration directory.
  ansible.builtin.file:
    path: "{{ aerospace__borders_configuration_directory }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"
    state: directory

- name: Place borders configuration.
  ansible.builtin.template:
    src: bordersrc.j2
    dest: "{{ aerospace__borders_configuration_directory }}/bordersrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"
  notify: Reload borders.

- name: Install sketchybar.
  community.general.homebrew:
    name: felixkratz/formulae/sketchybar
    state: present

- name: Create sketchybar configuration and plugin directory.
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ aerospace__sketchybar_configuration_directory }}"
    - "{{ aerospace__sketchybar_configuration_directory }}/plugins"
    - "{{ aerospace__sketchybar_configuration_directory }}/items"

- name: Get latest version for icon_map.lua for sketchybar font.
  block:
    - name: Get latest version of sketchybar-font
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ aerospace__sketchybar_repository }}/releases/latest"
        body_format: json
      register: _sketchybar_github_release
      until: _sketchybar_github_release.status == 200
      retries: 5
      check_mode: false

    - name: Set sketchybar-font version.
      ansible.builtin.set_fact:
        aerospace__sketchybar_font_version: "{{ _sketchybar_github_release.json.tag_name }}"

- name: Download icon_map.lua plugin for sketchybar.
  ansible.builtin.get_url:
    url: "https://github.com/{{ aerospace__sketchybar_repository }}/releases/download/{{ aerospace__sketchybar_font_version }}/icon_map.lua"
    dest: "{{ aerospace__sketchybar_configuration_directory }}/plugins/icon_map.lua"
    mode: "0755"

- name: Install sketchybar app font.
  community.general.homebrew_cask:
    name: font-sketchybar-app-font
    state: present

- name: Place sketchybar configuration.
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ aerospace__sketchybar_configuration_directory }}/{{ item | basename | splitext | first }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"
  notify: Reload sketchybar.
  loop: "{{ lookup('fileglob', 'templates/sketchybar/*', wantlist=True) }}"

- name: Place sketchybar items
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ aerospace__sketchybar_configuration_directory }}/items/{{ item | basename }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"
  notify: Reload sketchybar.
  loop: "{{ lookup('fileglob', 'files/sketchybar/items/*', wantlist=True) }}"

- name: Install sketchybar LUA module.
  ansible.builtin.git: # noqa: latest
    repo: https://github.com/FelixKratz/SbarLua.git
    dest: "{{ ansible_env.HOME }}/.local/share/SbarLua.git"
  notify: Install SbarLua.
