---

# Default applications to install via homebrew
packages__homebrew_packages:
  - ansible
  - ansible-lint
  - bats
  - bluetoothconnector
  - checkbashisms
  - coreutils
  - ctags
  - dockutil
  - dos2unix
  - exercism
  - fd
  - fping
  - gh
  - gnu-sed
  - gnu-tar
  - httpie
  - iperf3
  - jq
  - lesspipe
  - macvim
  - mas
  - moreutils
  - nmap
  - p7zip
  - perl
  - perltidy
  - telnet
  - terminal-notifier
  - the_silver_searcher
  - tmux
  - topgrade
  - watch
  - wget
  - xz

# Additional applications to install via homebrew
packages__homebrew_packages_extra: []

packages__homebrew_blacklist:
  - flake8
  - hub
  - podman

packages__homebrew_blacklist_extra: []

# Homebrew taps do add
packages__homebrew_taps:
  - homebrew/cask-fonts

# Additional homebrew taps to add
packages__homebrew_taps_extra: []

# Default casks to install via homebrew
packages__homebrew_casks:
  - 1password
  - 1password-cli
  - alfred
  - appcleaner
  - autodesk-fusion360
  - balenaetcher
  - firefox
  - font-fira-code-nerd-font
  - font-hack-nerd-font
  - google-chrome
  - gpg-suite
  - hammerspoon
  - hiddenbar
  - iterm2
  - keybase
  - logitech-camera-settings
  - menumeters
  - nextcloud
  - nrlquaker-winbox
  - sensiblesidebuttons
  - signal
  - sonos
  - spotify
  - teamviewer
  - telegram
  - visual-studio-code
  - whatsapp
  - wireshark

# Additional casks to install via homebrew
packages__homebrew_casks_extra: []

packages__homebrew_casks_blacklist:
  - aerial
  - font-firacode-nerd-font
  - font-firacode-nerd-font-mono

packages__homebrew_casks_blacklist_extra: []

# Default applications to install from Mac AppStore
packages__mas:
  - {id: 497799835, name: 'Xcode'}
  - {id: 1475387142, name: 'Tailscale'}
  - {id: 1451685025, name: 'WireGuard'}

# Additional applications to install from Mac AppStore
packages__mas_extra: []

# Packages for a default linux host
packages__linux_packages:
  - curl
  - git
  - vim
  - zsh
