---
- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_system }}.yml"
    - default.yml

- name: Ensure yadm is installed
  block:
    - name: Ensure yadm is installed (OSX)
      ansible.builtin.include_tasks: install/macos.yml
      when: ansible_os_family == 'Darwin'

    - name: Get latest yadm from GitHub
      ansible.builtin.include_tasks: install/github.yml
      when: ansible_system == 'Linux'

- name: Clone dotfiles with yadm
  ansible.builtin.command:
    cmd: "{{ yadm_path }} clone -f --bootstrap {{ yadm__dotfiles_repo }}"
    creates: ~/.local/share/yadm/repo.git
  register: yadm__clone_dotfiles
  until: yadm__clone_dotfiles is succeeded
  when: yadm__dotfiles_repo is defined
