---

- name: Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_system }}.yml"
    - "default.yml"

- name: Ensure yadm is installed
  block:
    - name: Ensure yadm is installed (OSX)
      include_tasks: install/macos.yml
      when: ansible_distribution == 'MacOSX'

    - name: Get latest yadm from GitHub
      include_tasks: install/github.yml
      when: ansible_system == 'Linux'

- name: Clone dotfiles with yadm
  shell: '{{ yadm_path }}/yadm clone -f --bootstrap {{ yadm__dotfiles_repo }}'
  args:
    creates: '~/.config/yadm/repo.git'
  register: yadm__clone_dotfiles
  until: yadm__clone_dotfiles is succeeded
  when: yadm__dotfiles_repo is defined

- name: Change shell of user to zsh
  user:
    name: "{{ ansible_user }}"
    shell: "/bin/zsh"
  become: true
