---

- name: Create local bin path
  ansible.builtin.file:
    path: "{{ yadm_path }}"
    state: directory
    recurse: true
    mode: "0755"

- name: Download yadm from GitHub
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/TheLocehiliosan/yadm/{{ yadm_version }}/yadm"
    checksum: "{{ yadm_gh_checksum | default(omit) }}"
    dest: "{{ yadm_path }}/yadm"
    mode: "0755"
