---
- name: Install iTerm2.
  community.general.homebrew_cask:
    name: iterm2
    state: present

- name: Create directory for dynamic profiles.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0755

- name: Install my iTerm profile as a dynamic profile.
  ansible.builtin.template:
    src: templates/stierbn.json.j2
    dest: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles/stierbn.json"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644

- name: Set default profile in iTerm2.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: Default Bookmark Guid
    type: string
    value: "{{ ansible_hostname | to_uuid }}"
    state: present

- name: Automatically check for new versions of iTerm2.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: SUEnableAutomaticChecks
    type: bool
    value: true
    state: present

- name: Check for beta versions for auto update.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: CheckTestRelease
    type: bool
    value: true
    state: present

- name: Allow terminal apps to access the pasteboard.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: AllowClipboardAccess
    type: bool
    value: true
    state: present

- name: Convert DOS newlines to Unix when using advanced paste.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: ConvertDosNewlines
    type: bool
    value: true
    state: present

- name: Keep window size the same when tabbar shows/hides.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PreserveWindowSizeWhenTabBarVisibilityChanges
    type: bool
    value: true
    state: present

- name: Enable smart window placement.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: SmartPlacement
    type: bool
    value: true
    state: present

- name: Show a border around windows.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: UseBorder
    type: bool
    value: false
    state: present

- name: Draw a line under the tab bar.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: EnableDivisionView
    type: bool
    value: false
    state: present

- name: Don't warn about short lived sessions.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: "NeverWarnAboutShortLivedSessions_{{ ansible_hostname | to_uuid }}"
    type: bool
    value: true
    state: present

- name: Set appearance theme.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: TabStyleWithAutomaticOption
    type: int
    value: 5
    state: present

- name: Dim inactive split panes.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: SplitPaneDimmingAmount
    type: float
    value: 0.25
    state: present

- name: Hide scroll bars.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: HideScrollbar
    type: bool
    value: "{{ terminal__hide_scrollbars | bool }}"
    state: present

- name: Disable escape sequences to clear history.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PreventEscapeSequenceFromClearingHistory
    type: bool
    value: true
    state: present

- name: Disable warning about sending input to multiple panes.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: NoSyncSuppressBroadcastInputWarning
    type: int
    value: 1
    state: present

- name: Disable Tip of the Day.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: NoSyncPermissionToShowTip
    type: bool
    value: false
    state: present

- name: Disable warning about displaying images.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: NoSyncSuppressDownloadConfirmation
    type: int
    value: 1
    state: present

- name: Disable automatic Debug Logging in iTerm2.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: StartDebugLoggingAutomatically
    type: int
    value: 0
    state: present

- name: Set profile window on startup.
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: OpenBookmark
    type: int
    value: 0
    state: present
