---
dock__tilesize: 22

packages__homebrew_packages_extra:
  - arduino-cli

packages__homebrew_casks_extra:
  - blackhole-2ch
  - element
  - openscad
  - prusaslicer
  - signal

packages__mas_extra:
  - { id: 948660805, name: AusweisApp2 }
  - { id: 905953485, name: NordVPN }

packages__mas_blacklist_extra:
  - { id: 1592844577, name: Neo Noir }

dockitems_persist:
  - name: iTerm
    pos: 1
  - name: Firefox
    path: /Applications/Firefox.app/
    pos: 2
  - name: Mail
    pos: 3
  - name: Calendar
    pos: 4
  - name: Photos
    pos: 5
  - name: Telegram
    path: /Applications/Telegram.app/
    pos: 6
  - name: Spotify
    pos: 7
  - name: Visual Studio Code
    path: /Applications/Visual Studio Code.app/
    pos: 8

dockitems_remove:
  - App Store
  - Contacts
  - FaceTime
  - Google Chrome
  - Launchpad
  - Maps
  - Messages
  - Notes
  - Reminders
  - Safari
  - System Preferences
  - iBooks

osx__wallpaper: ~/Nextcloud_p/Wallpapers/Desert.heic
