---

- block:
  - name: 'Set HOME as default location for new Finder windows'
    osx_defaults:
      domain: 'com.apple.finder'
      key: 'NewWindowTarget'
      type: 'string'
      value: 'PfLo'
      state: 'present'
    notify: Restart Finder

  - name: 'Set HOME as default location for new Finder windows/2'
    osx_defaults:
      domain: 'com.apple.finder'
      key: 'NewWindowTargetPath'
      type: 'string'
      value: "file://{{ ansible_env['HOME'] }}"
      state: 'present'
    notify: Restart Finder

- name: Finder - show status bar
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowStatusBar'
    type: 'bool'
    value: 'true'
    state: 'present'
  notify: Restart Finder

# Four-letter codes for the other view modes: `icnv`, `Nlsv`, `clmv`, `Flwv`
- name: Finder - Use list view in all windows by default
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'FXPreferredViewStyle'
    type: 'string'
    value: 'Nlsv'
    state: 'present'
  notify: Restart Finder

- name: Enable snap-to-grid for icons on the desktop and in other icon views
  include_tasks: defaults/finder.arrangeby.yml
  loop:
    - ':DesktopViewSettings:IconViewSettings:arrangeBy'
    - ':FK_StandardViewSettings:IconViewSettings:arrangeBy'
    - ':StandardViewSettings:IconViewSettings:arrangeBy'

- name: 'Configure "Connected Servers" on Desktop'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowMountedServersOnDesktop'
    type: 'bool'
    value: 'true'
    state: 'present'
  notify: Restart Finder

- name: 'Configure "Hard Drives" on Desktop'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowHardDrivesOnDesktop'
    type: 'bool'
    value: 'false'
    state: 'present'
  notify: Restart Finder

- name: 'Configure "External Hard Drives" on Desktop'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowExternalHardDrivesOnDesktop'
    type: 'bool'
    value: 'true'
    state: 'present'
  notify: Restart Finder

- name: 'Configure "Removable Media" on Desktop'
  osx_defaults:
    domain: 'com.apple.finder'
    key: 'ShowRemovableMediaOnDesktop'
    type: 'bool'
    value: 'true'
    state: 'present'
  notify: Restart Finder

- name: ActivityMonitor - Show main window when launching
  osx_defaults:
    domain: 'com.apple.ActivityMonitor'
    key: 'OpenMainWindow'
    type: 'bool'
    value: 'true'
    state: 'present'

- name: ActivityMonitor - Show CPU usage in Dock icon
  osx_defaults:
    domain: 'com.apple.ActivityMonitor'
    key: 'IconType'
    type: 'int'
    value: '5'
    state: 'present'

- name: ActivityMonitor - Show all processes
  osx_defaults:
    domain: 'com.apple.ActivityMonitor'
    key: 'ShowCategory'
    type: 'int'
    value: '0'
    state: 'present'

- name: Trackpad - Enable tap to click for this user and for the login screen
  include_tasks: defaults/trackpad.taptoclick.yml

- name: Enable full keyboard access for all controls
  osx_defaults:
    domain: 'NSGlobalDomain'
    key: 'AppleKeyboardUIMode'
    type: 'int'
    value: '3'
    state: 'present'

- name: Don't write .DS_Store files on network or USB volumes
  osx_defaults:
    domain: 'com.apple.desktopservices'
    key: '{{ item }}'
    type: 'bool'
    value: 'true'
    state: 'present'
  loop:
    - DSDontWriteNetworkStores
    - DSDontWriteUSBStores

- name: Disable the macOS Crash reporter
  osx_defaults:
    domain: 'com.apple.CrashReporter'
    key: 'DialogType'
    type: 'string'
    value: 'none'
    state: 'present'

- name: Set TimeMachine to high priority.
  sysctl:
    name: 'debug.lowpri_throttle_enabled'
    value: '0'
    reload: false   # Does not work on macOS
    state: present
  become: true
