---

- name: Create custom fact directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    recurse: true
    state: directory
    owner: root
    group: wheel
    mode: 0755
  become: true

- name: Insert custom fact for connected keyboards
  ansible.builtin.copy:
    src: files/osx-keyboards.fact
    dest: /etc/ansible/facts.d/osx_keyboards.fact
    mode: 0755
  become: true

- name: Re-run setup to use custom facts
  ansible.builtin.setup:
    filter: ansible_local

- name: Remap Keys
  ansible.builtin.include_tasks: remap_keys.yml
  loop: "{{ ansible_local.osx_keyboards.keyboards }}"

# I often slip to alt-space when using the alt-button to create special
# characters. This creates a NBSP, and it sucks.
- name: Create KeyBindings directory.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Library/KeyBindings"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0755
    state: directory

- name: Replace non-breaking space (alt+space) with normal space.
  ansible.builtin.copy:
    content: |
      {
        "~ " = (insertText:, " ");
      }
    dest: "{{ ansible_env.HOME }}/Library/KeyBindings/DefaultKeyBinding.dict"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
