---

- name: Create custom fact directory
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory
    owner: root
    group: wheel
    mode: 0755
  become: yes

- name: Insert custom fact for connected keyboards
  copy:
    src: files/osx-keyboards.fact
    dest: /etc/ansible/facts.d/osx_keyboards.fact
    mode: 0755
  become: yes

- name: Re-run setup to use custom facts
  setup: filter=ansible_local

- name: Remap Keys
  include_tasks: remap_keys.yml
  loop: "{{ ansible_local.osx_keyboards.keyboards }}"
