---

- name: Configure Keyboard special keys.
  ansible.builtin.include_tasks: keyboard.yml
  when: osx__remap_caps2esc|bool

- name: Set OSX configuration via defaults command.
  ansible.builtin.include_tasks: defaults.yml

- name: Setup sudo via TouchID.
  ansible.builtin.include_tasks: sudo_touchid.yml
  when: osx__sudo_touchid|bool

- name: Setup sudo via WatchID.
  ansible.builtin.include_tasks: sudo_watchid.yml
  when: osx__sudo_watchid|bool

- name: Setup wallpaper.
  ansible.builtin.include_tasks: wallpaper.yml
  when: osx__wallpaper is defined and osx__wallpaper | length > 0
