---

- include_tasks: keyboard.yml
  when: osx__remap_caps2esc|bool

- include_tasks: defaults.yml

- include_tasks: sudo_touchid.yml
  when: osx__sudo_touchid|bool

- include_tasks: sudo_watchid.yml
  when: osx__sudo_watchid|bool