---

- name: Enable Citrix services on startup.
  community.general.launchd:
    name: "{{ item }}"
    state: started
  become: true
  loop:
    - com.citrix.ServiceRecords
    - com.citrix.ReceiverHelper
    - com.citrix.AuthManager_Mac
    - com.citrix.WebLauncher
