---

- name: Check current keyboard mapping
  ansible.builtin.shell: |
    set -o pipefail
    defaults -currentHost read -g com.apple.keyboard.modifiermapping.{{ item.VENDOR_ID }}-{{ item.PRODUCT_ID }}-0 | grep -E 'HIDKeyboardModifierMappingDst = 30064771113|HIDKeyboardModifierMappingSrc = 30064771129' | wc -l | sed -e 's/ *//g'
  args:
    executable: /bin/bash
  register: osx__current_kb_mapping
  changed_when: no
  check_mode: no

- name: Remap Capslock to Escape for all keyboards
  ansible.builtin.shell: "defaults -currentHost write -g com.apple.keyboard.modifiermapping.{{ item.VENDOR_ID }}-{{ item.PRODUCT_ID }}-0 -array '<dict><key>HIDKeyboardModifierMappingDst</key><integer>30064771113</integer><key>HIDKeyboardModifierMappingSrc</key><integer>30064771129</integer></dict>'"
  when: osx__current_kb_mapping.stdout|int != 2
