---
- name: Detect TouchID support.
  ansible.builtin.command:
    cmd: pgrep ControlStrip
  register: osx__touch_id_result
  changed_when: false # noqa no-changed-when
  failed_when: false

- name: Enable TouchID for sudo commands.
  community.general.pamd:
    name: sudo
    type: auth
    control: sufficient
    module_path: pam_smartcard.so
    new_type: auth
    new_control: sufficient
    new_module_path: pam_tid.so
    state: before
  when: osx__touch_id_result.rc == 0 and osx__touch_id_result.stdout | length > 0
  become: true
