---

- name: Detect TouchID support.
  ansible.builtin.command:
    cmd: "pgrep ControlStrip"
  ignore_errors: True
  register: touch_id_result
  changed_when: False # noqa no-changed-when

- name: Enable TouchID for sudo commands.
  ansible.builtin.lineinfile:
    path: '/etc/pam.d/sudo'
    line: 'auth       sufficient     pam_tid.so'
    insertbefore: '^auth       sufficient     pam_smartcard.so$'
  when: touch_id_result.rc == 0 and touch_id_result.stdout|length > 0
  become: True