---

- name: Clone pam-watchid repository.
  ansible.builtin.git:
    repo: https://github.com/biscuitehh/pam-watchid
    dest: "{{ osx__pam_watchid_dir }}"
    version: main

- name: Build the module.
  ansible.builtin.command:
    chdir: "{{ osx__pam_watchid_dir }}"
    cmd: "swiftc watchid-pam-extension.swift -o {{ osx__pam_watchid_library_name }} -target {{ osx__pam_watchid_target }} -emit-library"
    creates: "{{ osx__pam_watchid_library_name }}"

- name: Make sure local pam-directory exists.
  ansible.builtin.file:
    path: "{{ osx__pam_watchid_dest }}"
    owner: root
    group: staff
    mode: "0755"
    state: directory
  become: true

- name: Install the module.
  ansible.builtin.copy:
    src: "{{ osx__pam_watchid_dir }}/{{ osx__pam_watchid_library_name }}"
    dest: "{{ osx__pam_watchid_dest }}/{{ osx__pam_watchid_library_name }}.{{ osx__pam_watchid_library_version }}"
    owner: root
    group: wheel
    mode: "0444"
    remote_src: true
  become: true

- name: Enable WatchID for sudo commands.
  community.general.pamd:
    name: sudo
    type: auth
    control: sufficient
    module_path: pam_tid.so
    new_type: auth
    new_control: sufficient
    new_module_path: pam_watchid.so
    state: before
  become: true
