---
- name: Install desktoppr helper utility.
  community.general.homebrew_cask:
    name: desktoppr
    state: present

- name: Check if wallpaper file exists.
  ansible.builtin.stat:
    path: "{{ osx__wallpaper | expanduser }}"
  changed_when: false
  register: osx__wallpaper_file

- name: Get information about current wallpaper.
  ansible.builtin.command: desktoppr
  changed_when: false
  register: osx__wallpaper_current
  ignore_errors: false

- name: Set new wallpaper.
  ansible.builtin.command: desktoppr {{ osx__wallpaper }}
  register: _desktoppr_output
  changed_when: true
  failed_when: _desktoppr_output.rc != 0
  when:
    - osx__wallpaper_file.stat.exists
    - osx__wallpaper_current.stdout_lines[0] != osx__wallpaper_file.stat.path
