---

- name: Install Tunneblick application.
  community.general.homebrew_cask:
    name: tunnelblick
    state: installed

- name: Create Tunneblick Configuration.
  ansible.builtin.include_tasks:
    file: build_config.yml
  loop: "{{ tunnelblick_configurations }}"
  loop_control:
    label: "{{ tblk_config.name | default('config' ~ tblk_config_idx) }}"
    loop_var: tblk_config
    index_var: tblk_config_idx
