---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 13 * * 0

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Run yamllint.
        uses: bewuethr/yamllint-action@v1

      - name: Run ansible-lint.
        uses: ansible/ansible-lint@main
        with:
          requirements_file: requirements.yml

  integration:
    name: Integration
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - macos-14
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Uninstall GitHub Actions' built-in Homebrew.
        run: tests/uninstall-homebrew.sh

      - name: Uninstall GitHub Actions' built-in browser installs.
        run: |
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app

      - name: Setup python.
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip

      - name: Install ansible via pip.
        run: pip install -r tests/requirements.txt

      - name: Set up the test environment.
        run: |
          cp tests/ansible.cfg ./ansible.cfg
          cp tests/inventory ./inventory
          cp tests/config.yml ./config.yml
          ansible-galaxy install -r requirements.yml

      - name: Test the playbook's syntax.
        run: ansible-playbook setup.yml --syntax-check

      - name: Test the playbook.
        run: ansible-playbook setup.yml
        env:
          ANSIBLE_FORCE_COLOR: 1

      - name: Idempotence check.
        run: |
          idempotence=$(mktemp)
          ansible-playbook setup.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: 1
